### PR TITLE
Bump JAR to version 2.48.2

### PR DESCRIPTION
**Pull request by mstred**
Updated JAR file to current Selenium server release (version 2,48,2). Tests are passing, except for old binary deprecation assertion in 1st test case (`old_binary_triggers_deprecation`).

### CODE REVIEW

**Comment by PedroTroller** [comment]
:+1:

**Comment by jeremykendall** [comment]
Bump. We need this for new tests cases at @GraphStory.

**Comment by gunfrank** [comment]
@sveneisenschmidt u there?

**Comment by sveneisenschmidt** [comment]
I am. Sorry for the delay. Going to update to the newest version later the
day.

Am Dienstag, 5. Januar 2016 schrieb gunfrank :

**Comment by sveneisenschmidt** [comment]
Just checking the md5 of the supplied jar file.

**Comment by jeremykendall** [comment]
Thanks!

**Pull request merged**
