### PR TITLE
Adding Chrome webdriver support

### PR DESCRIPTION
**Pull request by igorsantos07**
As made on https://github.com/edmondscommerce/selenium-server, I've added the latest Selenium Chrome Driver binary to this project, as well as added the Selenium flag.
Now it's possible to run both Chrome and Firefox instances from this project :)

I've downloaded the driver from here: http://chromedriver.storage.googleapis.com/index.html

As there was some shellmagic to resolve the actual bin directory, I've converted the script into PHP. That will make maintenance easier (as the project is PHP anyways) and also helped me to use the same path for the chromedriver as well.

### CODE REVIEW

**Comment by sveneisenschmidt** [comment]
Hello igorsantos07,

thank you for the additions you brought in here. I have some question first:

1. Why do you refer to shellmagic in the bash script and replaced it wiht php? I don't feel confident using `shell_exec` to execute the java binary.

2. You modified the path in README.md to `vendor/bin/selenium-server-standalone` but isn't it `bin/selenium-server-standalone`? What is normal project usage and as not?

Your changes affect several different features and I'd love to see them as different PRs so we can talk about it independently. The chromedriver would be a nice addition to the project. Though I am not sure about the other changes you mode but I am open to everything.

Thank you
Sven

**Comment by igorsantos07** [comment]
Hey man! Thanks for the follow up!

I've changed it to PHP because 1. I think it makes sense, so we don't mix
languages in such a simple project and 2. I know bits of shell, but - as
any other developer that could stumble on this project - a lot of PHP.
Thus, it makes sense to use PHP as scripting language, as that would also
foster future contributions.

On using `shell_exec`, it works just fine. I've tested it a couple of times
during development, and you can try it as well.

Finally, about the path issue: when you install the package through
composer, the executables are symlinked into `project_root/vendor/bin/` by
default. Using `bin` as directory only works from inside the package.

**Comment by sveneisenschmidt** [comment]
```
Hey man! Thanks for the follow up!

I've changed it to PHP because 1. I think it makes sense, so we don't mix
languages in such a simple project and 2. I know bits of shell, but - as
any other developer that could stumble on this project - a lot of PHP.
Thus, it makes sense to use PHP as scripting language, as that would also
foster future contributions.
```

Thank you for your clarifications. I am still not sold about switching to php. For most of the users the bash implementation works. But I can see the project switching to php if some issues are resolved first. 

```
Finally, about the path issue: when you install the package through
composer, the executables are symlinked into `project_root/vendor/bin/` by
default. Using `bin` as directory only works from inside the package.
``` 
(Did you remove this one?)

Can you verify this with a test? If you are right this is a bug that needs to be solved. Running the library from `bin` must work.  I am going to provide a Travis CI configuration and a phpunit setup. Would you mind to write a test to show the problem?

Famous example symlinking a executable to `bin`:
* https://github.com/sebastianbergmann/phpunit/blob/master/composer.json#L51
* https://github.com/Behat/Behat/blob/master/composer.json#L55
* https://github.com/doctrine/doctrine2/blob/master/composer.json#L39

**Comment by sveneisenschmidt** [comment]
I think I found the issue with `bin`. Are you using this project as a standalone project or inside a composer-powered php project?

**Comment by sveneisenschmidt** [comment]
Hey @igorsantos07

Let's get rid of bash and use php instead. Would you mind to rebuild your PR on the current dev-master except the README.md changes and the executable lies now in `bin`.

I am looking forward for your changes and will write the tests to ensure everything is still working the same way the users except it.

**Pull request closed without merging**
